services:
  ja3proxy:
    image: ghcr.io/lylemi/ja3proxy:latest
    build: .
    entrypoint:
      [
        "/app/ja3proxy",
        "--ca-cert",
        "/app/credentials/cert.pem",
        "--ca-key",
        "/app/credentials/key.pem",
        "--tls-fingerprint",
        "360Browser@7.5"
      ]
    ports:
      - 8080:8080
    volumes:
      - ./credentials:/app/credentials
